### ISSUE TITLE
[BUG] Attribute sets that apply to multiple files are not deterministic

### ISSUE THREAD

**Issue by jpower432** [uor-framework/uor-client-go#92]
**Description**

The attributes are not merged properly when a dataset configuration consists if a file matches multiple patterns.

**Steps to reproduce the issue:**
1. Create a dsconfig
```
kind: DataSetConfiguration
apiVersion: client.uor-framework.io/v1alpha1
collection:
  files:
    - file: "*"
      attributes:
        publisher: "me"
    - file: "leaf.txt"
      attributes:
        animal: "fish"
        habitat: "ocean"
        size: "small"
        scales: 7
        color: "blue"
        leaf: true
    - file: "root.txt"
      attributes:
        leaf: false
```
2. Create a workspace:
```
mkdir leaf-workspace
echo "leaf" > leaf-workspace/leaf.txt
```
4. `uor-client-go build collection leaf-workspace localhost:5001/leaf:latest --dsconfig leaf-dataset-config.yaml`

**Describe the results you received:**

The digest changes on each run

**Describe the results you expected:**

The digest to be the same on everyrun

**What version of the UOR client are you using:**

v0.3.0
